name: Teste de Sanidade do Workflow

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer Ola
        run: echo "O workflow de teste de sanidade funcionou!"
