name: Teste de Gatilho de Segurança

on:
  workflow_dispatch:
  dependabot_alert:
    types: [created]

jobs:
  teste-de-gatilho:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar qual gatilho foi usado
        run: echo "O workflow foi acionado pelo evento ${{ github.event_name }}"
